project_id = "cdpfamanvoredyputkky"

[functions.google-calendar-callback]
verify_jwt = false

[functions.google-calendar-sync]
verify_jwt = false

[functions.google-calendar-event]
verify_jwt = false

[functions.spotify-callback]
verify_jwt = false

[functions.spotify-refresh]
verify_jwt = false

[functions.spotify-client-id]
verify_jwt = false