using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

// Focus Bloom is deliberately self-contained: open Main.unity and press Play.
public class FocusBloomBootstrap : MonoBehaviour
{
    [Serializable] public class Profile { public string university="Universidad Nacional Mayor de San Marcos", career="Ingeniería Informática"; public int cycle=5, targetCredits=210, wellbeing=72, level=5, xp=4250, seeds=28, streak=6; }
    [Serializable] public class Course { public string id, code, title, zone, monument, status, prereq; public int credits, cycle, grade; }
    [Serializable] public class Task { public string id, course, title, kind, deadline; public int minutes, difficulty, reward, pomodoros; public bool done; }
    [Serializable] public class Session { public string date, notes; public int minutes, xp; }
    [Serializable] public class Save { public Profile profile=new Profile(); public List<Course> courses=new List<Course>(); public List<Task> tasks=new List<Task>(); public List<Session> sessions=new List<Session>(); }

    private Save game; private string screen="world", selectedCourse="", activeMission="", notes=""; private int focusMinutes=25; private float sessionStarted; private Vector2 curriculumScroll, profileScroll; private GUIStyle title, small, button, card, muted, courseTitle, landmarkButton, textButton; private Texture2D softTexture;
    private readonly Color night=new Color(0.035f,.09f,.18f), panel=new Color(.055f,.15f,.27f), mint=new Color(.49f,.89f,.68f), gold=new Color(.98f,.77f,.34f);
    private const string SaveKey="focus-bloom-unity-v1";

    void Awake(){ game=Load(); }
    void OnGUI(){ SetupStyles(); GUI.color=night; GUI.DrawTexture(new Rect(0,0,Screen.width,Screen.height),Texture2D.whiteTexture); GUI.color=Color.white; DrawHeader(); if(screen=="world") DrawWorld(); else if(screen=="curriculum") DrawCurriculum(); else DrawProfile(); if(!string.IsNullOrEmpty(activeMission)) DrawFocusOverlay(); }
    void SetupStyles(){
        title=new GUIStyle(GUI.skin.label){fontSize=22,fontStyle=FontStyle.Bold,normal={textColor=Color.white},wordWrap=true};
        small=new GUIStyle(GUI.skin.label){fontSize=12,normal={textColor=new Color(.65f,.78f,.9f)},wordWrap=true}; muted=new GUIStyle(small){alignment=TextAnchor.MiddleCenter};
        button=new GUIStyle(GUI.skin.button){fontSize=12,fontStyle=FontStyle.Bold,alignment=TextAnchor.MiddleCenter,normal={textColor=Color.white,background=MakeTex(panel)},hover={background=MakeTex(new Color(.12f,.32f,.42f))},padding=new RectOffset(8,8,7,7)};
        card=new GUIStyle(GUI.skin.box){normal={background=MakeTex(panel)},padding=new RectOffset(15,15,13,13)}; courseTitle=new GUIStyle(title){fontSize=14};
        landmarkButton=new GUIStyle(GUI.skin.button){fontSize=25,alignment=TextAnchor.MiddleCenter,normal={textColor=Color.white,background=SoftTexture()},hover={background=SoftTexture()}};
        textButton=new GUIStyle(GUI.skin.button){fontSize=12,fontStyle=FontStyle.Bold,alignment=TextAnchor.MiddleCenter,normal={textColor=new Color(.85f,.97f,.9f),background=MakeTex(new Color(0,0,0,0))},hover={textColor=gold,background=MakeTex(new Color(0,0,0,0))}};
    }
    Texture2D MakeTex(Color c){ var t=new Texture2D(1,1);t.SetPixel(0,0,c);t.Apply();return t; }
    Texture2D SoftTexture(){ if(softTexture!=null)return softTexture; const int n=96;softTexture=new Texture2D(n,n,TextureFormat.RGBA32,false);for(int y=0;y<n;y++)for(int x=0;x<n;x++){float dx=(x/(float)(n-1)-.5f)*2f,dy=(y/(float)(n-1)-.5f)*2f;float d=Mathf.Sqrt(dx*dx+dy*dy);float a=Mathf.Clamp01((1f-d)*4.5f);softTexture.SetPixel(x,y,new Color(1,1,1,a));}softTexture.Apply();return softTexture; }
    void DrawHeader(){
        GUI.Box(new Rect(0,0,Screen.width,68),"",card); GUI.Label(new Rect(26,15,220,32),"🌿 FOCUS <color=#F6D369>BLOOM</color>",new GUIStyle(title){richText=true,fontSize=18});
        GUI.Label(new Rect(260,14,260,18),$"{game.profile.career} · Ciclo {game.profile.cycle}",small); GUI.Label(new Rect(260,34,260,18),game.profile.university,small);
        GUI.Label(new Rect(Screen.width-390,14,150,20),$"Nivel {game.profile.level} · {game.profile.xp:N0} XP",small); GUI.Label(new Rect(Screen.width-390,36,150,16),$"Créditos {ApprovedCredits()}/{game.profile.targetCredits}",small); DrawBar(new Rect(Screen.width-230,40,110,6),ApprovedCredits()/(float)game.profile.targetCredits,mint);
        if(GUI.Button(new Rect(Screen.width-100,19,76,29),"Demo",button)) ResetDemo();
    }
    void DrawWorld(){
        var world=new Rect(0,68,Screen.width,Screen.height-68); DrawSky(world); DrawOrganicBiome(world,0,new Color(.04f,.55f,.62f),new Color(.96f,.42f,.25f),"Costa del Génesis");DrawOrganicBiome(world,1,new Color(.04f,.27f,.15f),new Color(.16f,.55f,.24f),"Arboleda Algorítmica");DrawOrganicBiome(world,2,new Color(.22f,.11f,.13f),new Color(.78f,.27f,.12f),"Forja de Software");DrawOrganicBiome(world,3,new Color(.03f,.16f,.27f),new Color(.12f,.42f,.58f),"Ciudadela de Datos");DrawOrganicBiome(world,4,new Color(.13f,.08f,.28f),new Color(.62f,.34f,.83f),"Observatorio de Grado");DrawWindingPath(world); DrawWorldLandmarks(world); DrawFloatingMissions(world); DrawNav(); if(!string.IsNullOrEmpty(selectedCourse)) DrawCourseInspector();
    }
    void DrawSky(Rect r){for(int i=0;i<18;i++){float t=i/17f;GUI.color=Color.Lerp(new Color(.13f,.04f,.23f),new Color(.96f,.35f,.2f),t*.65f);GUI.DrawTexture(new Rect(r.x,r.y+i*r.height/18f,r.width,r.height/18f+1),Texture2D.whiteTexture);}GUI.color=new Color(1,.74f,.38f,.72f);GUI.DrawTexture(new Rect(r.x+r.width*.39f,r.y+30,72,72),SoftTexture());GUI.color=Color.white;}
    void DrawOrganicBiome(Rect r,int index,Color low,Color high,string label){float width=r.width/5f;float x=r.x+index*width;float baseY=r.y+r.height*.53f+(index%2)*22; bool fog=game.courses.Where(c=>c.zone==label).Any()&&game.courses.Where(c=>c.zone==label).All(c=>c.status=="locked"); Color active=fog?Color.Lerp(low,Color.gray,.55f):low;for(int i=0;i<17;i++){float sx=x-70+(i*47%((int)width+90));float sy=baseY+(i*73%185)-75;float size=100+(i%4)*46;GUI.color=Color.Lerp(active,high,(i%5)/5f);GUI.DrawTexture(new Rect(sx,sy,size,size*.72f),SoftTexture());}for(int i=0;i<8;i++){float tx=x+20+(i*59%Mathf.Max(40,(int)width-20));float ty=baseY-84+(i%3)*38;GUI.color=Color.Lerp(high,Color.black,.25f);GUI.DrawTexture(new Rect(tx,ty,38,105),SoftTexture());GUI.color=high;GUI.DrawTexture(new Rect(tx-22,ty-32,84,70),SoftTexture());}GUI.color=Color.white;GUI.Label(new Rect(x+18,r.y+24,width-36,20),label,new GUIStyle(small){fontStyle=FontStyle.Bold,alignment=TextAnchor.MiddleCenter,normal={textColor=new Color(1,1,1,.78f)}});if(fog)GUI.Label(new Rect(x+18,baseY+80,width-36,22),"✦ Aún cubierto por niebla",muted);}
    void DrawWindingPath(Rect r){for(int i=0;i<90;i++){float t=i/89f;float x=r.x+38+t*(r.width-76);float y=r.y+r.height*.70f+Mathf.Sin(t*9f)*42+Mathf.Sin(t*22f)*13;float s=16+Mathf.Sin(i)*3;GUI.color=Color.Lerp(new Color(.71f,.46f,.22f),new Color(1,.87f,.55f),t);GUI.DrawTexture(new Rect(x-s/2,y-s/2,s,s),SoftTexture());}GUI.color=Color.white;}
    void DrawWorldLandmarks(Rect r){var positions=new Dictionary<string,Vector2>{{"Costa del Génesis",new Vector2(.09f,.54f)},{"Arboleda Algorítmica",new Vector2(.28f,.40f)},{"Forja de Software",new Vector2(.48f,.49f)},{"Ciudadela de Datos",new Vector2(.69f,.38f)},{"Observatorio de Grado",new Vector2(.89f,.35f)}};var offsets=new Vector2[]{new Vector2(0,0),new Vector2(.05f,.13f),new Vector2(-.05f,.15f)};var counts=new Dictionary<string,int>();foreach(var c in game.courses){int n=counts.ContainsKey(c.zone)?counts[c.zone]:0;counts[c.zone]=n+1;Vector2 p=positions[c.zone]+offsets[Mathf.Min(n,offsets.Length-1)];float size=c.status=="approved"?72:60;var cr=new Rect(r.x+p.x*r.width-size/2,r.y+p.y*r.height-size/2,size,size);Color col=c.status=="approved"?mint:c.status=="in_progress"?gold:c.status=="locked"?new Color(.45f,.5f,.58f):Color.white;GUI.color=new Color(col.r,col.g,col.b,.72f);string icon=c.status=="locked"?"🔒":c.monument=="forge"?"⚒":c.monument=="tower"?"♜":c.monument=="observatory"?"◉":c.monument=="grove"?"♣":"▰";if(GUI.Button(cr,icon,landmarkButton))selectedCourse=c.id;GUI.color=Color.white;GUI.Label(new Rect(cr.x-52,cr.yMax+1,cr.width+104,18),c.title,new GUIStyle(small){alignment=TextAnchor.MiddleCenter,normal={textColor=Color.white}});}}
    void DrawFloatingMissions(Rect r){var missions=GetMissions();GUI.Label(new Rect(26,r.y+20,260,26),"TU EXPEDICIÓN DE HOY",new GUIStyle(small){fontStyle=FontStyle.Bold,normal={textColor=mint}});for(int i=0;i<missions.Count;i++){var m=missions[i];float y=r.y+52+i*36;GUI.Label(new Rect(26,y,310,22),$"{(m.kind=="Urgente"?"✦":"◌")} {m.title}  ·  +{m.xp} XP",new GUIStyle(small){normal={textColor=Color.white}});if(GUI.Button(new Rect(340,y-3,94,25),$"{m.minutes} min  ›",textButton)){activeMission=m.id;focusMinutes=m.minutes;sessionStarted=Time.realtimeSinceStartup;}}GUI.Label(new Rect(r.xMax-244,r.y+24,220,18),$"Salud  {game.profile.wellbeing}%   ·   🔥 {game.profile.streak} días",new GUIStyle(small){alignment=TextAnchor.MiddleRight});DrawBar(new Rect(r.xMax-190,r.y+48,165,4),game.profile.wellbeing/100f,mint);}
    void DrawNav(){var y=Screen.height-52;string[] names={"Mundo Central","Malla & Grafo","Perfil"};string[] ids={"world","curriculum","profile"};for(int i=0;i<3;i++)if(GUI.Button(new Rect(25+i*145,y,132,28),names[i],textButton))screen=ids[i];}
    void DrawCourseInspector(){var c=game.courses.First(x=>x.id==selectedCourse);var center=new Rect(Screen.width-285,Screen.height-282,235,235);GUI.color=new Color(.03f,.11f,.19f,.9f);GUI.DrawTexture(center,SoftTexture());GUI.color=Color.white;if(GUI.Button(new Rect(center.xMax-40,center.y+24,20,20),"×",textButton))selectedCourse="";GUI.Label(new Rect(center.x+35,center.y+46,165,18),c.code+" · "+c.zone,new GUIStyle(small){alignment=TextAnchor.MiddleCenter});GUI.Label(new Rect(center.x+30,center.y+70,175,40),c.title,new GUIStyle(title){fontSize=18,alignment=TextAnchor.MiddleCenter});GUI.Label(new Rect(center.x+30,center.y+118,175,22),$"{c.credits} créditos · {StatusLabel(c.status)}",new GUIStyle(small){alignment=TextAnchor.MiddleCenter});if(c.status=="locked")GUI.Label(new Rect(center.x+30,center.y+145,175,34),"Completa: "+PrereqNames(c),new GUIStyle(small){alignment=TextAnchor.MiddleCenter});else if(GUI.Button(new Rect(center.x+54,center.y+178,126,28),c.status=="approved"?"✦ Consolidado":"Florecer curso",textButton)){c.status="approved";c.grade=Mathf.Max(15,c.grade);UnlockCourses();SaveGame();}}
    string StatusLabel(string x){return x=="approved"?"Aprobado":x=="in_progress"?"En progreso":x=="locked"?"Bloqueado":"Pendiente";} string PrereqNames(Course c){return string.Join(" y ",c.prereq.Split(',').Where(x=>x.Length>0).Select(x=>game.courses.FirstOrDefault(q=>q.id==x)?.title));}
    public class MissionVM { public string id,kind,title,description; public int minutes,xp; }
    List<MissionVM> GetMissions(){var list=new List<MissionVM>();var pending=game.tasks.Where(t=>!t.done).OrderBy(t=>DateTime.Parse(t.deadline)).ToList();if(pending.Count>0){var t=pending[0];list.Add(new MissionVM{id=t.id,kind="Urgente",title=t.title,description=CourseTitle(t.course)+" · deadline cercano",minutes=t.minutes,xp=t.reward});}if(pending.Count>1){var t=pending[1];list.Add(new MissionVM{id=t.id,kind="Avance",title=t.title,description="Un paso real para expandir tu mundo",minutes=t.minutes,xp=t.reward});}if(game.profile.wellbeing<78)list.Add(new MissionVM{id="recovery",kind="Recuperación",title="Recuperación consciente",description="Protege tu energía y tu racha",minutes=15,xp=12});return list;}
    void DrawFocusOverlay(){GUI.color=new Color(0,0,0,.74f);GUI.DrawTexture(new Rect(0,0,Screen.width,Screen.height),Texture2D.whiteTexture);GUI.color=new Color(.06f,.25f,.28f,.96f);var orb=new Rect(Screen.width/2-250,Screen.height/2-250,500,500);GUI.DrawTexture(orb,SoftTexture());GUI.color=Color.white;var m=GetMissions().FirstOrDefault(x=>x.id==activeMission);GUI.Label(new Rect(orb.x+85,orb.y+64,330,18),"SESIÓN DE ENFOQUE",new GUIStyle(small){alignment=TextAnchor.MiddleCenter,normal={textColor=mint}});GUI.Label(new Rect(orb.x+75,orb.y+92,350,45),m?.title??"Expedición",new GUIStyle(title){fontSize=23,alignment=TextAnchor.MiddleCenter});GUI.Label(new Rect(orb.x+70,orb.y+140,360,18),"Lluvia suave · una sola cosa a la vez",new GUIStyle(small){alignment=TextAnchor.MiddleCenter});GUI.Label(new Rect(orb.x+75,orb.y+170,350,58),$"{focusMinutes:00}:00",new GUIStyle(title){fontSize=48,alignment=TextAnchor.MiddleCenter});if(GUI.Button(new Rect(orb.x+115,orb.y+237,75,25),"25 min",textButton))focusMinutes=25;if(GUI.Button(new Rect(orb.x+210,orb.y+237,75,25),"45 min",textButton))focusMinutes=45;if(GUI.Button(new Rect(orb.x+305,orb.y+237,75,25),"Libre",textButton))focusMinutes=15;GUI.Label(new Rect(orb.x+110,orb.y+275,280,18),"Notas de la expedición",new GUIStyle(small){alignment=TextAnchor.MiddleCenter});notes=GUI.TextArea(new Rect(orb.x+110,orb.y+298,280,45),notes);if(GUI.Button(new Rect(orb.x+125,orb.y+360,250,31),$"Completar · +{m?.xp??0} XP",textButton))CompleteMission(m);}
    void CompleteMission(MissionVM m){if(m==null){activeMission="";return;}if(m.id=="recovery")game.profile.wellbeing=Mathf.Min(100,game.profile.wellbeing+8);else {var t=game.tasks.First(x=>x.id==m.id);t.done=true;t.pomodoros+=Mathf.Max(1,focusMinutes/25);game.profile.wellbeing=Mathf.Max(0,game.profile.wellbeing-1);}game.profile.xp+=m.xp;game.profile.seeds++;game.profile.level=game.profile.xp/1000+1;game.sessions.Add(new Session{date=DateTime.Now.ToString("yyyy-MM-dd HH:mm"),minutes=focusMinutes,notes=notes,xp=m.xp});notes="";activeMission="";SaveGame();}
    void DrawCurriculum(){DrawNav();GUI.Label(new Rect(32,100,750,45),"Tu malla es el camino.",new GUIStyle(title){fontSize=36});GUI.Label(new Rect(34,152,650,22),"Actualiza cursos: los nodos dependientes se desbloquean al aprobar sus prerrequisitos.",small);curriculumScroll=GUI.BeginScrollView(new Rect(28,194,Screen.width-56,Screen.height-270),curriculumScroll,new Rect(0,0,Screen.width-90,950));for(int cycle=1;cycle<=10;cycle++){var y=(cycle-1)*93;GUI.Label(new Rect(10,y+20,58,32),cycle.ToString("00")+"\nCICLO",small);var items=game.courses.Where(c=>c.cycle==cycle).ToList();for(int i=0;i<items.Count;i++){var c=items[i];var r=new Rect(85+i*240,y+8,220,77);Color color=c.status=="approved"?mint:c.status=="in_progress"?gold:c.status=="locked"?Color.gray:Color.white;GUI.color=new Color(color.r,color.g,color.b,.18f);GUI.Box(r,"",card);GUI.color=Color.white;GUI.Label(new Rect(r.x+12,r.y+9,195,17),c.code+" · "+StatusLabel(c.status),small);GUI.Label(new Rect(r.x+12,r.y+28,195,19),c.title,courseTitle);if(c.status!="locked"&&GUI.Button(new Rect(r.x+12,r.y+51,95,20),c.status=="approved"?"Aprobado":"Aprobar",button)){c.status="approved";c.grade=16;UnlockCourses();SaveGame();}if(c.status=="locked")GUI.Label(new Rect(r.x+12,r.y+52,195,19),"🔒 "+PrereqNames(c),small);} }GUI.EndScrollView();}
    void DrawProfile(){DrawNav();GUI.Label(new Rect(32,100,600,45),"Bitácora de aventurero",new GUIStyle(title){fontSize=36});var data=new[]{("Promedio ponderado",Average().ToString("0.0")+" /20"),("Créditos aprobados",ApprovedCredits()+" /"+game.profile.targetCredits),("Nivel del Reino",game.profile.level.ToString()),("Racha actual",game.profile.streak+" días")};for(int i=0;i<data.Length;i++){var r=new Rect(35+i*210,175,190,105);GUI.Box(r,"",card);GUI.Label(new Rect(r.x+14,r.y+18,160,18),data[i].Item1,small);GUI.Label(new Rect(r.x+14,r.y+45,160,35),data[i].Item2,new GUIStyle(title){fontSize=25});}GUI.Box(new Rect(35,305,650,180),"",card);GUI.Label(new Rect(55,324,590,25),"🏆 Logros del Reino",title);GUI.Label(new Rect(55,358,590,22),"🌿 Primer bosque algorítmico  ·  ⚒ Forja de software activa  ·  ✦ Explorador constante",small);GUI.Label(new Rect(55,402,590,24),"⌛ Historial de sesiones",courseTitle);profileScroll=GUI.BeginScrollView(new Rect(55,431,590,40),profileScroll,new Rect(0,0,560,Mathf.Max(40,game.sessions.Count*25)));for(int i=0;i<game.sessions.Count;i++){var s=game.sessions[game.sessions.Count-1-i];GUI.Label(new Rect(0,i*25,550,20),$"{s.date} · {s.minutes} min · +{s.xp} XP  {s.notes}",small);}GUI.EndScrollView();}
    int ApprovedCredits(){return game.courses.Where(c=>c.status=="approved").Sum(c=>c.credits);} float Average(){var x=game.courses.Where(c=>c.status=="approved"&&c.grade>0).ToList();return x.Count==0?0:x.Sum(c=>c.grade*c.credits)/(float)x.Sum(c=>c.credits);} string CourseTitle(string id){return game.courses.FirstOrDefault(c=>c.id==id)?.title??"Curso";}
    void UnlockCourses(){foreach(var c in game.courses.Where(c=>c.status=="locked")){var prereqs=c.prereq.Split(',').Where(x=>x.Length>0);if(prereqs.All(p=>game.courses.Any(x=>x.id==p&&x.status=="approved")))c.status="pending";}}
    Save Load(){try{if(PlayerPrefs.HasKey(SaveKey))return JsonUtility.FromJson<Save>(PlayerPrefs.GetString(SaveKey));}catch{}return Demo();} void SaveGame(){PlayerPrefs.SetString(SaveKey,JsonUtility.ToJson(game));PlayerPrefs.Save();}void ResetDemo(){game=Demo();SaveGame();}
    Save Demo(){var s=new Save();s.courses=new List<Course>{C("mat1","MAT101","Matemática I",5,1,17,"approved","Costa del Génesis","library",""),C("mat2","MAT201","Matemática II",5,2,16,"approved","Costa del Génesis","tower","mat1"),C("prog","INF201","Programación I",4,2,18,"approved","Arboleda Algorítmica","grove","mat1"),C("algo","INF301","Algoritmos y Estructuras",5,3,15,"approved","Arboleda Algorítmica","tower","prog,mat2"),C("db","INF401","Bases de Datos",4,4,16,"approved","Ciudadela de Datos","observatory","algo"),C("soft","INF501","Ingeniería de Software",5,5,0,"in_progress","Forja de Software","forge","algo"),C("net","INF502","Redes de Computadoras",4,5,0,"in_progress","Forja de Software","tower","prog"),C("ia","INF601","Inteligencia Artificial",4,6,0,"pending","Ciudadela de Datos","observatory","algo"),C("dist","INF701","Sistemas Distribuidos",4,7,0,"locked","Ciudadela de Datos","tower","soft,net"),C("thesis","INF1001","Proyecto de Grado",8,10,0,"locked","Observatorio de Grado","observatory","dist")};s.tasks=new List<Task>{T("t1","algo","Preparar examen de Algoritmos","examen",1,40,3,50),T("t2","soft","Diagrama de arquitectura Bloom","proyecto",3,25,2,25),T("t3","net","Lectura: capa de transporte","lectura",0,20,1,15)};return s;}
    Course C(string id,string code,string title,int cr,int cycle,int grade,string status,string zone,string monument,string pre){return new Course{id=id,code=code,title=title,credits=cr,cycle=cycle,grade=grade,status=status,zone=zone,monument=monument,prereq=pre};}Task T(string id,string c,string title,string kind,int days,int min,int diff,int reward){return new Task{id=id,course=c,title=title,kind=kind,deadline=DateTime.Today.AddDays(days).ToString("o"),minutes=min,difficulty=diff,reward=reward};}
    void DrawBar(Rect r,float value,Color c){GUI.color=new Color(1,1,1,.15f);GUI.DrawTexture(r,Texture2D.whiteTexture);GUI.color=c;GUI.DrawTexture(new Rect(r.x,r.y,r.width*Mathf.Clamp01(value),r.height),Texture2D.whiteTexture);GUI.color=Color.white;}
}
