import { FormEvent, useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import {
  BookOpenCheck,
  GraduationCap,
  Plus,
  Sparkles,
  Trash2,
} from 'lucide-react';
import { toast } from 'sonner';
import { useAuth } from '@/hooks/useAuth';
import { supabase } from '@/integrations/supabase/client';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Progress } from '@/components/ui/progress';

type AcademicPlan = {
  id: string;
  name: string;
  total_credits: number;
};

type Course = {
  id: string;
  code: string | null;
  name: string;
  cycle: number | null;
  credits: number;
};

type AcademicRecord = {
  id: string;
  grade: number | null;
  status: 'pending' | 'approved' | 'failed' | 'in_progress';
  academic_courses: Course | null;
};

// The database types are generated by Supabase. Regenerate them after applying
// the migration so these casts can be removed.
const academicDb = supabase as any;

export function AcademicProgressPanel() {
  const { user } = useAuth();
  const queryClient = useQueryClient();

  const [planName, setPlanName] = useState('');
  const [totalCredits, setTotalCredits] = useState('');
  const [courseName, setCourseName] = useState('');
  const [courseCode, setCourseCode] = useState('');
  const [courseCredits, setCourseCredits] = useState('');
  const [courseCycle, setCourseCycle] = useState('');
  const [grade, setGrade] = useState('');

  const { data, isLoading } = useQuery({
    queryKey: ['academic-progress', user?.id],
    enabled: !!user,
    queryFn: async () => {
      const { data: plan, error: planError } = await academicDb
        .from('academic_plans')
        .select('id, name, total_credits')
        .eq('user_id', user!.id)
        .order('created_at', { ascending: false })
        .limit(1)
        .maybeSingle();

      if (planError) throw planError;
      if (!plan) return { plan: null, records: [] as AcademicRecord[] };

      const { data: records, error: recordsError } = await academicDb
        .from('academic_records')
        .select('id, grade, status, academic_courses(id, code, name, cycle, credits)')
        .eq('user_id', user!.id)
        .order('updated_at', { ascending: false });

      if (recordsError) throw recordsError;

      return {
        plan: plan as AcademicPlan,
        records: (records ?? []) as AcademicRecord[],
      };
    },
  });

  const metrics = useMemo(() => {
    const records = data?.records ?? [];
    const approved = records.filter(
      (record) =>
        record.status === 'approved' &&
        record.grade !== null &&
        record.academic_courses
    );

    const approvedCredits = approved.reduce(
      (sum, record) => sum + Number(record.academic_courses!.credits),
      0
    );

    const weightedGradeTotal = approved.reduce(
      (sum, record) =>
        sum + Number(record.grade) * Number(record.academic_courses!.credits),
      0
    );

    const totalCredits = Number(data?.plan?.total_credits ?? 0);
    const progress = totalCredits
      ? Math.min(100, Math.round((approvedCredits / totalCredits) * 100))
      : 0;

    const xp = approved.reduce(
      (sum, record) =>
        sum +
        Math.round(
          Number(record.academic_courses!.credits) *
            100 *
            (Number(record.grade) / 20)
        ),
      0
    );

    return {
      approvedCredits,
      progress,
      xp,
      weightedGrade: approvedCredits
        ? (weightedGradeTotal / approvedCredits).toFixed(2)
        : '—',
      level: Math.min(11, Math.floor(progress / 10) + 1),
    };
  }, [data]);

  const invalidate = () =>
    queryClient.invalidateQueries({ queryKey: ['academic-progress', user?.id] });

  const createPlan = useMutation({
    mutationFn: async (event: FormEvent) => {
      event.preventDefault();
      const credits = Number(totalCredits);

      if (!user || !planName.trim() || !Number.isFinite(credits) || credits <= 0) {
        throw new Error('Escribe el nombre de tu carrera y sus créditos totales.');
      }

      const { error } = await academicDb.from('academic_plans').insert({
        user_id: user.id,
        name: planName.trim(),
        total_credits: credits,
      });

      if (error) throw error;
    },
    onSuccess: () => {
      toast.success('Tu malla personal fue creada.');
      invalidate();
    },
    onError: (error: Error) => toast.error(error.message),
  });

  const addRecord = useMutation({
    mutationFn: async (event: FormEvent) => {
      event.preventDefault();

      if (!user || !data?.plan) throw new Error('Primero crea tu malla.');
      const credits = Number(courseCredits);
      const courseGrade = Number(grade);

      if (
        !courseName.trim() ||
        !Number.isFinite(credits) ||
        credits <= 0 ||
        !Number.isFinite(courseGrade) ||
        courseGrade < 0 ||
        courseGrade > 20
      ) {
        throw new Error('Completa nombre, créditos y una nota entre 0 y 20.');
      }

      const { data: course, error: courseError } = await academicDb
        .from('academic_courses')
        .insert({
          plan_id: data.plan.id,
          code: courseCode.trim() || null,
          name: courseName.trim(),
          credits,
          cycle: courseCycle ? Number(courseCycle) : null,
        })
        .select('id')
        .single();

      if (courseError) throw courseError;

      const { error: recordError } = await academicDb
        .from('academic_records')
        .insert({
          user_id: user.id,
          course_id: course.id,
          grade: courseGrade,
          status: courseGrade >= 11 ? 'approved' : 'failed',
        });

      if (recordError) throw recordError;
    },
    onSuccess: () => {
      setCourseName('');
      setCourseCode('');
      setCourseCredits('');
      setCourseCycle('');
      setGrade('');
      toast.success('Curso registrado. Tu progreso fue recalculado.');
      invalidate();
    },
    onError: (error: Error) => toast.error(error.message),
  });

  const removeRecord = useMutation({
    mutationFn: async (courseId: string) => {
      const { error } = await academicDb
        .from('academic_courses')
        .delete()
        .eq('id', courseId);

      if (error) throw error;
    },
    onSuccess: () => {
      toast.success('Curso eliminado y progreso recalculado.');
      invalidate();
    },
    onError: (error: Error) => toast.error(error.message),
  });

  if (isLoading) {
    return <div className="card-calm p-5 text-sm text-muted-foreground">Cargando progreso académico...</div>;
  }

  if (!data?.plan) {
    return (
      <section className="card-calm p-5">
        <div className="mb-4 flex items-center gap-3">
          <div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-primary/10">
            <GraduationCap className="h-6 w-6 text-primary" />
          </div>
          <div>
            <p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
              Mapa de carrera
            </p>
            <h2 className="text-lg font-bold text-foreground">Crea tu meta personal</h2>
          </div>
        </div>

        <p className="mb-4 text-sm text-muted-foreground">
          Tu avance se calculará solo contra los créditos de tu propia malla.
        </p>

        <form className="space-y-3" onSubmit={(event) => createPlan.mutate(event)}>
          <Input
            placeholder="Carrera, por ejemplo: Ingeniería Informática"
            value={planName}
            onChange={(event) => setPlanName(event.target.value)}
          />
          <Input
            type="number"
            min="1"
            step="0.5"
            placeholder="Total de créditos de tu malla"
            value={totalCredits}
            onChange={(event) => setTotalCredits(event.target.value)}
          />
          <Button className="w-full gap-2" disabled={createPlan.isPending}>
            <BookOpenCheck className="h-4 w-4" />
            Crear mi mapa de carrera
          </Button>
        </form>
      </section>
    );
  }

  return (
    <section className="card-calm space-y-5 p-5">
      <div className="flex items-start justify-between gap-3">
        <div className="flex items-center gap-3">
          <div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-primary/10">
            <GraduationCap className="h-6 w-6 text-primary" />
          </div>
          <div>
            <p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
              Tu mapa de carrera
            </p>
            <h2 className="text-lg font-bold text-foreground">{data.plan.name}</h2>
          </div>
        </div>

        <div className="rounded-xl bg-amber-400/15 px-3 py-2 text-right">
          <p className="text-[10px] font-semibold uppercase text-amber-700 dark:text-amber-300">Nivel</p>
          <p className="text-lg font-bold text-amber-700 dark:text-amber-300">{metrics.level}</p>
        </div>
      </div>

      <div>
        <div className="mb-1.5 flex justify-between text-xs">
          <span className="text-muted-foreground">Créditos conquistados</span>
          <span className="font-semibold text-foreground">
            {metrics.approvedCredits} / {data.plan.total_credits} ({metrics.progress}%)
          </span>
        </div>
        <Progress value={metrics.progress} className="h-3" />
      </div>

      <div className="grid grid-cols-3 gap-2">
        <div className="rounded-xl bg-muted p-3 text-center">
          <p className="text-lg font-bold">{metrics.approvedCredits}</p>
          <p className="text-[10px] text-muted-foreground">CRÉDITOS</p>
        </div>
        <div className="rounded-xl bg-muted p-3 text-center">
          <p className="text-lg font-bold">{metrics.weightedGrade}</p>
          <p className="text-[10px] text-muted-foreground">PROMEDIO</p>
        </div>
        <div className="rounded-xl bg-muted p-3 text-center">
          <p className="flex items-center justify-center gap-1 text-lg font-bold">
            <Sparkles className="h-4 w-4 text-amber-500" /> {metrics.xp}
          </p>
          <p className="text-[10px] text-muted-foreground">XP ACADÉMICO</p>
        </div>
      </div>

      <form className="space-y-2 rounded-2xl border border-border p-3" onSubmit={(event) => addRecord.mutate(event)}>
        <p className="text-sm font-semibold">Registrar curso en la ficha</p>
        <Input
          placeholder="Nombre del curso"
          value={courseName}
          onChange={(event) => setCourseName(event.target.value)}
        />
        <div className="grid grid-cols-2 gap-2">
          <Input
            placeholder="Código (opcional)"
            value={courseCode}
            onChange={(event) => setCourseCode(event.target.value)}
          />
          <Input
            type="number"
            min="1"
            placeholder="Ciclo"
            value={courseCycle}
            onChange={(event) => setCourseCycle(event.target.value)}
          />
          <Input
            type="number"
            min="0.5"
            step="0.5"
            placeholder="Créditos"
            value={courseCredits}
            onChange={(event) => setCourseCredits(event.target.value)}
          />
          <Input
            type="number"
            min="0"
            max="20"
            step="0.1"
            placeholder="Nota (0 a 20)"
            value={grade}
            onChange={(event) => setGrade(event.target.value)}
          />
        </div>
        <Button type="submit" size="sm" className="w-full gap-2" disabled={addRecord.isPending}>
          <Plus className="h-4 w-4" />
          Guardar y recalcular
        </Button>
      </form>

      <div className="space-y-2">
        <p className="text-sm font-semibold">Cursos registrados</p>
        {data.records.length === 0 ? (
          <p className="text-sm text-muted-foreground">Aún no registraste cursos. Puedes transcribirlos de tu ficha de notas.</p>
        ) : (
          data.records.map((record) => {
            const course = record.academic_courses;
            if (!course) return null;

            return (
              <div key={record.id} className="flex items-center gap-3 rounded-xl bg-muted px-3 py-2">
                <div className="min-w-0 flex-1">
                  <p className="truncate text-sm font-medium">{course.name}</p>
                  <p className="text-xs text-muted-foreground">
                    {course.credits} créditos · {record.status === 'approved' ? 'Aprobado' : 'No aprobado'} · Nota {record.grade ?? '—'}
                  </p>
                </div>
                <Button
                  type="button"
                  variant="ghost"
                  size="icon"
                  className="shrink-0 text-muted-foreground hover:text-destructive"
                  onClick={() => removeRecord.mutate(course.id)}
                  aria-label={'Eliminar ' + course.name}
                >
                  <Trash2 className="h-4 w-4" />
                </Button>
              </div>
            );
          })
        )}
      </div>
    </section>
  );
}
